export const tagList = [
  { name: "a", class: null },
  { name: "abbr", class: null },
  { name: "acronym", class: null },
  { name: "address", class: null },
  { name: "applet", class: null },
  { name: "area", class: null },
  { name: "article", class: null },
  { name: "aside", class: null },
  { name: "audio", class: null },
  { name: "b", class: null },
  { name: "base", class: null },
  { name: "basefont", class: null },
  { name: "bdi", class: null },
  { name: "bdo", class: null },
  { name: "big", class: null },
  { name: "blockquote", class: null },
  { name: "body", class: null },
  { name: "br", class: null },
  { name: "button", class: null },
  { name: "canvas", class: null },
  { name: "caption", class: null },
  { name: "center", class: null },
  { name: "cite", class: null },
  { name: "code", class: null },
  { name: "col", class: null },
  { name: "colgroup", class: null },
  { name: "data", class: null },
  { name: "datalist", class: null },
  { name: "dd", class: null },
  { name: "del", class: null },
  { name: "details", class: null },
  { name: "dfn", class: null },
  { name: "dialog", class: null },
  { name: "dir", class: null },
  { name: "div", class: null },
  { name: "dl", class: null },
  { name: "dt", class: null },
  { name: "em", class: null },
  { name: "embed", class: null },
  { name: "fieldset", class: null },
  { name: "figcaption", class: null },
  { name: "figure", class: null },
  { name: "font", class: null },
  { name: "footer", class: null },
  { name: "form", class: null },
  { name: "frame", class: null },
  { name: "frameset", class: null },
  { name: "h1", class: "h1" },
  { name: "h2", class: "h2" },
  { name: "h3", class: "h3" },
  { name: "h4", class: "h4" },
  { name: "h5", class: "h5" },
  { name: "h5", class: "h6" },
  { name: "head", class: null },
  { name: "header", class: null },
  { name: "hr", class: null },
  { name: "html", class: null },
  { name: "i", class: null },
  { name: "iframe", class: null },
  { name: "img", class: null },
  { name: "input", class: null },
  { name: "ins", class: null },
  { name: "kbd", class: null },
  { name: "label", class: null },
  { name: "legend", class: null },
  { name: "li", class: null },
  { name: "link", class: null },
  { name: "main", class: null },
  { name: "map", class: null },
  { name: "mark", class: null },
  { name: "meta", class: null },
  { name: "meter", class: null },
  { name: "nav", class: null },
  { name: "noframes", class: null },
  { name: "noscript", class: null },
  { name: "object", class: null },
  { name: "ol", class: null },
  { name: "optgroup", class: null },
  { name: "option", class: null },
  { name: "output", class: null },
  { name: "p", class: null },
  { name: "param", class: null },
  { name: "picture", class: null },
  { name: "pre", class: null },
  { name: "progress", class: null },
  { name: "q", class: null },
  { name: "rp", class: null },
  { name: "rt", class: null },
  { name: "ruby", class: null },
  { name: "s", class: null },
  { name: "samp", class: null },
  { name: "script", class: "code" },
  { name: "section", class: null },
  { name: "select", class: null },
  { name: "small", class: null },
  { name: "source", class: null },
  { name: "span", class: null },
  { name: "strike", class: null },
  { name: "strong", class: null },
  { name: "style", class: null },
  { name: "sub", class: null },
  { name: "summary", class: null },
  { name: "sup", class: null },
  { name: "svg", class: null },
  { name: "table", class: null },
  { name: "tbody", class: null },
  { name: "td", class: null },
  { name: "template", class: null },
  { name: "textarea", class: null },
  { name: "tfoot", class: null },
  { name: "th", class: null },
  { name: "thead", class: null },
  { name: "time", class: null },
  { name: "title", class: null },
  { name: "tr", class: null },
  { name: "track", class: null },
  { name: "tt", class: null },
  { name: "u", class: null },
  { name: "ul", class: null },
  { name: "var", class: null },
  { name: "video", class: null },
  { name: "wbr", class: null }
];

export const tagList1 = [
  "a",
  "abbr",
  "acronym",
  "address",
  "applet",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "basefont",
  "bdi",
  "bdo",
  "big",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "dir",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "font",
  "footer",
  "form",
  "frame",
  "frameset",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "meta",
  "meter",
  "nav",
  "noframes",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "small",
  "source",
  "span",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "svg",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tt",
  "u",
  "ul",
  "var",
  "video",
  "wbr"
];
